### ISSUE TITLE
Update to new APIs

### ISSUE THREAD

**Issue by ivucica** [JonathonReinhart/rawrsa#2]
Hi,

The OpenSSL issue https://github.com/openssl/openssl/issues/1491 mentions a change in the public API documented in [OpenSSL 1.1.0 Changes](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes) document.

Certain fields became private, and accessor methods were added.

```
diff --git a/main.c b/main.c
index 5bff3a1..da31ef0 100644
--- a/main.c
+++ b/main.c
@@ -124,8 +124,7 @@ int main(int argc, char *argv[])
         err("RSA_new() failed\n");
         return 1;
     }
-    rsa->e = exp;
-    rsa->n = mod;
+    RSA_set0_key(rsa, mod, exp, NULL);
 
     /* Write PEM-encoded RSA public key to stdout */
     if (!PEM_write_RSA_PUBKEY(stdout, rsa)) {

```

**Comment by JonathonReinhart** [comment]
Thanks for pointing this out, Ivan. I haven't yet familiarized myself with the OpenSSL 1.1.0 changes, so I appreciate you so concisely describing what needs to happen in this simple case.

It's my understanding that, in addition to your patch, I would need to add the following code to support versions older than 1.1.0. Is that your understanding as well?
```c
 #if OPENSSL_VERSION_NUMBER < 0x10100000L

 int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d)
 {
    /* If the fields n and e in r are NULL, the corresponding input
     * parameters MUST be non-NULL for n and e.  d may be
     * left NULL (in case only the public key is used).
     */
    if ((r->n == NULL && n == NULL)
        || (r->e == NULL && e == NULL))
        return 0;

    if (n != NULL) {
        BN_free(r->n);
        r->n = n;
    }
    if (e != NULL) {
        BN_free(r->e);
        r->e = e;
    }
    if (d != NULL) {
        BN_free(r->d);
        r->d = d;
    }

    return 1;
 }

 #endif /* OPENSSL_VERSION_NUMBER < 0x10100000L */
```

Also, please feel free to submit a PR!

**Comment by ivucica** [comment]
Hi,

I am not actually very familiar with OpenSSL -- this solution was just the first thing that I found online. (Thank you for your project.)

Related to sending a PR -- I would, but I'm not fully certain my contracts allow me to submit even this two-line patch in the issue.

I would be able to do that super easily if the project included a license.

**Comment by JonathonReinhart** [comment]
Fixed. Thanks @ivucica!
